Repository rapidsai/devcontainers, pull requests merged in 2024-11, with the labels that each got.

#414 Fix kvikio casing and remove unnecessary rmm dependency
  features/src/rapids-build-utils/opt/rapids-build-utils/manifest.yaml
Labels: bug, non-breaking

#418 Remove nx-cugraph from cugraph
  features/src/rapids-build-utils/devcontainer-feature.json
  features/src/rapids-build-utils/opt/rapids-build-utils/manifest.yaml
Labels: breaking, improvement

#417 move cugraph projects around for 24.12
  features/src/rapids-build-utils/devcontainer-feature.json
  features/src/rapids-build-utils/opt/rapids-build-utils/manifest.yaml
Labels: breaking, improvement

#416 Add breaking change workflow trigger
  .github/workflows/trigger-breaking-change-alert.yaml
Labels: improvement, non-breaking

#419 Fix GitLab owner detection for nested org hierarchy
  features/src/utils/devcontainer-feature.json
  features/src/utils/opt/devcontainer/bin/gitlab/repo/clone.sh
Labels: bug, non-breaking
