Repository rapidsai/devcontainers, pull requests merged in 2025-01, with the labels that each got.

#438 add libraft wheels
  features/src/rapids-build-utils/devcontainer-feature.json
  features/src/rapids-build-utils/opt/rapids-build-utils/manifest.yaml
Labels: breaking, improvement, DO NOT MERGE

#437 remove cugraph-ops
  .devcontainer/build-rapids.sh
  .devcontainer/cuda11.8-conda/devcontainer.json
  .devcontainer/cuda11.8-pip/devcontainer.json
  .devcontainer/cuda12.0-conda/devcontainer.json
  .devcontainer/cuda12.0-pip/devcontainer.json
  .devcontainer/cuda12.2-conda/devcontainer.json
  .devcontainer/cuda12.2-pip/devcontainer.json
  .devcontainer/cuda12.5-conda/devcontainer.json
  .devcontainer/cuda12.5-pip/devcontainer.json
  .github/workflows/build-all-rapids-repos.yml
  features/src/rapids-build-utils/devcontainer-feature.json
  features/src/rapids-build-utils/opt/rapids-build-utils/manifest.yaml
Labels: breaking, improvement

#435 add libcugraph Python builds
  features/src/rapids-build-utils/opt/rapids-build-utils/manifest.yaml
Labels: breaking, improvement, DO NOT MERGE

#440 add libcuvs Python builds
  features/src/rapids-build-utils/devcontainer-feature.json
  features/src/rapids-build-utils/opt/rapids-build-utils/manifest.yaml
Labels: breaking, improvement

#441 Update to UCX 1.18
  features/src/ucx/devcontainer-feature.json
  matrix.yml
Labels: improvement, non-breaking

#442 add libcuml Python builds
  features/src/rapids-build-utils/devcontainer-feature.json
  features/src/rapids-build-utils/opt/rapids-build-utils/manifest.yaml
Labels: improvement, non-breaking

#443 use UCX 1.18.0 in pip devcontainers
  .devcontainer/cuda11.8-pip/devcontainer.json
  .devcontainer/cuda12.0-pip/devcontainer.json
  .devcontainer/cuda12.2-pip/devcontainer.json
  .devcontainer/cuda12.5-pip/devcontainer.json
Labels: breaking, improvement

#446 Forward-merge branch-25.02 to branch-25.04
  .devcontainer/cuda11.8-pip/devcontainer.json
  .devcontainer/cuda12.0-pip/devcontainer.json
  .devcontainer/cuda12.2-pip/devcontainer.json
  .devcontainer/cuda12.5-pip/devcontainer.json
  features/src/rapids-build-utils/devcontainer-feature.json
  features/src/rapids-build-utils/opt/rapids-build-utils/manifest.yaml
Labels: improvement, non-breaking
